name: Compile binaries
on: [pull_request, push, workflow_dispatch]

jobs:
  build:
    name: Build ${{ matrix.os }}-${{ matrix.feature_level }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        os: [linux, macos, windows, linux-arm, macos-arm, windows-arm]
        feature_level: [x86-64-v2, x86-64-v3, x86-64-v4]
        include:
          - os: linux
            runner: ubuntu-24.04
            toolchain: x86_64-unknown-linux-gnu
            artifact_path: target/release/target_compile_test
          - os: macos
            runner: macos-13 # Only free macos runner using x86
            toolchain: x86_64-apple-darwin
            artifact_path: target/release/target_compile_test
          - os: windows
            runner: windows-2025
            toolchain: x86_64-pc-windows-msvc
            artifact_path: target/release/target_compile_test.exe
          - os: linux-arm
            runner: ubuntu-24.04-arm
            toolchain: aarch64-unknown-linux-gnu
            artifact_path: target/release/target_compile_test
            feature_level: generic
          - os: macos-arm
            runner: macos-14 # Apparently macos-14 runners outperform macos-15
            toolchain: aarch64-apple-darwin
            artifact_path: target/release/target_compile_test
            feature_level: generic
          - os: windows-arm
            runner: windows-11-arm
            toolchain: aarch64-pc-windows-msvc
            artifact_path: target/release/target_compile_test.exe
            feature_level: generic
        exclude:
          - os: linux-arm
            feature_level: x86-64-v2
          - os: linux-arm
            feature_level: x86-64-v3
          - os: linux-arm
            feature_level: x86-64-v4
          - os: macos-arm
            feature_level: x86-64-v2
          - os: macos-arm
            feature_level: x86-64-v3
          - os: macos-arm
            feature_level: x86-64-v4
          - os: windows-arm
            feature_level: x86-64-v2
          - os: windows-arm
            feature_level: x86-64-v3
          - os: windows-arm
            feature_level: x86-64-v4

    env:
      RUSTFLAGS: -C target-cpu=${{ matrix.feature_level }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable-${{ matrix.toolchain }}
      - name: Update dependencies
        run: cargo update
      - name: Build
        run: cargo build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.feature_level }}
          path: ${{ matrix.artifact_path }}
          if-no-files-found: error
          retention-days: 1
